[package]
name = "cxc"
version = "0.1.0"
edition = "2021"

[dependencies]

logos = "0.12.0"
llvm-sys = "120"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm12-0"] }

memoize = "0.3.1"
bytemuck = { version = "1.12.3", optional = true, default-features = false }
slotmap = "1.0.6"
indexmap = "1.9.2"
passable = { git = "https://github.com/amjoshuamichael/passable" }

cxc_derive = { git = "https://github.com/amjoshuamichael/cxc_derive", optional = true }

# these libraries are re-exported into cxc

glam = { version = "0.22.0", optional = true }

[features]
default = ["cxc_derive"]
xc-debug = []
llvm-debug = []

[profile.bench]
debug = true

[profile.release]
opt-level = 3
