[package]
name = "cxc"
version = "0.1.0"
edition = "2021"

[dependencies]

logos = "0.12.0"

llvm-sys = { version = "150", optional = true }
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm15-0"], optional = true }
either = "1.8.1" # for use with inkwell

memoize = "0.3.1"
bytemuck = { version = "1.12.3", optional = true, default-features = false }
slotmap = "1.0.6"
indexmap = "1.9.2"
passable = { git = "https://github.com/amjoshuamichael/passable" }
lazy_static = "1.4.0"
rand = "0.8.5"
subenum = "1.0.1"

cxc_derive = { path = "https://github.com/amjoshuamichael/cxc_derive", optional = true }

# these libraries are re-exported into cxc

glam = { version = "0.22.0", optional = true }

[dev-dependencies]
serial_test = "1.0.0"

[features]
default = ["cxc_derive", "backend-llvm", "ffi-assertions"]
xc-debug = []
llvm-debug = []
backend-llvm = ["llvm-sys", "inkwell"]
show-bytes = []
ffi-assertions = []

[profile.bench]
opt-level = 3

[profile.release]
opt-level = 3
