[package]
name = "cxc"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.12.0"

llvm-sys = "120"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm12-0"] }

memoize = "0.3.1"

bytemuck = "1.12.3"

cxc_derive = { git = "https://github.com/amjoshuamichael/cxc_derive" }

# these libraries are re-exported into cxc

glam = { version = "0.22.0", optional = true }

[profile.bench]
debug = true
