[package]
name = "cxc"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.12.0"
inkwell = { git = "https://github.com/amjoshuamichael/inkwell", branch = "master", features = ["llvm12-0"] }
num-bigint = "0.4.3"
indexmap = "1.9.1"
