[package]
name = "cxc"
version = "0.1.0"
edition = "2021"

[dependencies]
logos = "0.12.0"
llvm-sys = "120"
inkwell = { git = "https://github.com/TheDan64/inkwell", branch = "master", features = ["llvm12-0"] }
